### ISSUE TITLE
Make web pack compatible.

### ISSUE THREAD

**Issue by giodamelio** [piuccio/cowsay#25]
I have been wanting to use `cowsay` in the web browser for awhile now. There is a [fork of this package](https://github.com/bushmango/cowsay-browser) makes it work, but the docs are not good, and it seems to me that it would be better to make it work on the upstream version.

I was wondering if you would be willing to accept a patch that refactors the loading of the cows to not use any node apis? I was thinking of converting the cow files into json, and writing a build script to convert the original versions to json versions. Should be relatively easy and work seamlessly on both Node.js and in the browser with something like Webpack or Browserify. Creating UMD bundles would also be a possibility.

**Comment by piuccio** [comment]
holy cow! I didn't expect people would use this module in a browser.

Sure it sounds like a good idea, well, as good as using cowsay in node. Let me find some time to think about it. Is it necessary to convert to JSON? Webpack has a plain text loader as well

**Comment by giodamelio** [comment]
That's a good point! I've never played around with it, but I don't see any
reason it wouldn't work.

Just to let you know, the reason I and many other people are using it is
that is has become part of the ciriculum at a coding bootcamp called Code
Fellows, we use it in a bunch of assignments on both the back end and front
end. A whole lot of people have use it to write basically the first Node
server they have ever written. It's pretty cool 😀

**Comment by piuccio** [comment]
@giodamelio Do you have time to check the branch `browser` and see if it works on your setup?

**Comment by giodamelio** [comment]
It works great. I didn't know webpack would use the `browser` field first!

One thing though, the `browser.js` is not exporting a default which breaks some code.

Adding `export default { say, think };` to the end of the file fixes it up just fine.

Thanks so much for doing this, I have to go look into rollup too now, seems pretty nice.

**Comment by piuccio** [comment]
> One thing though, the browser.js is not exporting a default which breaks some code.

What code is broken? I wanted to avoid having both a default and named exports

**Comment by piuccio** [comment]
Version `1.2.0` works in the browser

**Comment by giodamelio** [comment]
Awesome, thanks so much for making this happen.
