### ISSUE TITLE
Imports must start with "./" and not .cows

### ISSUE THREAD

**Issue by kevinsimper** [piuccio/cowsay#47]
![image](https://user-images.githubusercontent.com/1126497/50967031-33bc1880-14d7-11e9-9621-361856e14950.png)

**Comment by kevinsimper** [comment]
@piuccio This is a error in that the module does not conform to the es module spec :)

**Comment by piuccio** [comment]
It would help if you had some code to share.
Btw I don't know if es modules in the browser can handle text files

**Comment by kevinsimper** [comment]
```
import { say } from "cowsay";

console.log(say({ text: "grazing in the browser" }));
```

I guess that you are right :)
