### ISSUE TITLE
Introducing a fork

### ISSUE THREAD

**Issue by johnnysprinkles** [piuccio/cowsay#53]
I was a little confused by all the complexity going on with how .cow files are imported, and not really understanding why there's different documentation for browser usage and NodeJS usage. And I had issues with Webpack bundling, so I ended up largely rewriting your `cowsay` as a fork. It's pretty nice because it has all the cows just as JS modules and there's no filesystem reading.

Curious what  you think? Your cowsay is 7 years old? Javascript has come a long way since then!

https://github.com/johnnysprinkles/cowsay

**Comment by chobijaeyu** [comment]
yes,I just build failed with angular.wish it can be update
