### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by iliasmentz** [piuccio/cowsay#69]
Hi,

I am trying to use the `cowsay` with typescript and npm but I can't find the proper `@types` to install.
the results from `npm search @types/cowsay` are `No matches found for "@types/cowsay"`.

The error i am receivign when i am trying to use.
```
TSError: ⨯ Unable to compile TypeScript:
src/scrape/index.ts:5:25 - error TS7016: Could not find a declaration file for module 'cowsay'. 
'whatever-my-root-folder-is/node_modules/cowsay/index.js' implicitly has an 'any' type.
  Try `npm install @types/cowsay` if it exists or add a new declaration (.d.ts) file containing `declare module 'cowsay';`

5 import * as cowsay from 'cowsay';
```

any ideas? Thanks in advance!

**Comment by piuccio** [comment]
this might just be because I haven't published a new version to npm yet

**Comment by samhwang** [comment]
Hi @piuccio , is there a timeline of when you would release the new version to npm ? I would love to use this package in a typescript project. :D

**Comment by piuccio** [comment]
Hey, thanks for the reminder. I've just pushed a new version to npm. Hopefully it works, I haven't used this project in typescript yet so I can't check myself.
